@startuml c4-theme-default

!include http://plantuml.oss.manerfan.com/colors.puml
' uncomment the following line and comment the first to use locally
'!include colors.puml

' Colors
' ##################################
!ELEMENT_FONT_COLOR             = MD_WHITE

' Person
!PERSON_BG_COLOR                = MD_BLUE_800
!PERSON_BORDER_COLOR            = MD_BLUE_900
!EXTERNAL_PERSON_BG_COLOR       = MD_GRAY_700
!EXTERNAL_PERSON_BORDER_COLOR   = MD_GRAY_800

' System
!SYSTEM_BG_COLOR                = MD_BLUE_700
!SYSTEM_BORDER_COLOR            = MD_BLUE_800
!EXTERNAL_SYSTEM_BG_COLOR       = MD_GRAY_600
!EXTERNAL_SYSTEM_BORDER_COLOR   = MD_GRAY_700

' Database
!DATABASE_BG_COLOR              = MD_BLUE_700
!DATABASE_BORDER_COLOR          = MD_BLUE_800

' Actor
!ACTOR_BG_COLOR                 = MD_BLUE_800
!ACTOR_BORDER_COLOR             = MD_BLUE_900
!INTERNAL_ACTOR_BG_COLOR        = MD_GRAY_700
!INTERNAL_ACTOR_BORDER_COLOR    = MD_GRAY_800

' Container
!CONTAINER_BG_COLOR             = MD_BLUE_600
!CONTAINER_BORDER_COLOR         = MD_BLUE_600

' Component
!COMPONENT_BG_COLOR             = MD_BLUE_200
!COMPONENT_BORDER_COLOR         = MD_BLUE_300
!COMPONENT_FONT_COLOR           = Black
@enduml
