@startuml class-diagram-helper


!CLASS_LINE_FONT_SIZE = 12

!unquoted function Link_(e_alias1, e_alias2, e_label, e_direction="") 
    e_alias1 e_direction e_alias2 : "e_label"
!endfunction
!unquoted function Link_(e_alias1, e_alias2, e_label, e_techn, e_direction="") 
    e_alias1 e_direction e_alias2 : "e_label\n//<size:TECHN_FONT_SIZE>[e_techn]</size>//"
!endfunction

!unquoted function Link(e_from, e_to, e_label) 
    Link_(e_from,e_to, e_label, "-->")
!endfunction
!unquoted function Link(e_from, e_to, e_label, e_techn) 
    Link_(e_from,e_to, e_label, e_techn, "-->")
!endfunction

' 泛化 类继承
!unquoted function Generalize(e_from, e_to, e_label) 
    Link_(e_from,e_to, e_label, "--|>")
!endfunction
!unquoted function Generalize(e_from, e_to, e_label, e_techn) 
    Link_(e_from,e_to, e_label, e_techn, "--|>")
!endfunction
!unquoted function GeneralizeBack(e_from, e_to, e_label) 
    Link_(e_from,e_to, e_label, "<|--")
!endfunction
!unquoted function GeneralizeBack(e_from, e_to, e_label, e_techn) 
    Link_(e_from,e_to, e_label, e_techn, "<|--")
!endfunction

' 实现 
!unquoted function Realize(e_from, e_to, e_label) 
    Link_(e_from,e_to, e_label, "..|>")
!endfunction
!unquoted function Realize(e_from, e_to, e_label, e_techn) 
    Link_(e_from,e_to, e_label, e_techn, "..|>")
!endfunction
!unquoted function RealizeBack(e_from, e_to, e_label) 
    Link_(e_from,e_to, e_label, "<|..")
!endfunction
!unquoted function RealizeBack(e_from, e_to, e_label, e_techn) 
    Link_(e_from,e_to, e_label, e_techn, "<|..")
!endfunction

' 聚合 
!unquoted function Aggregation(e_from, e_to, e_label) 
    Link_(e_from,e_to, e_label, "--o")
!endfunction
!unquoted function Aggregation(e_from, e_to, e_label, e_techn) 
    Link_(e_from,e_to, e_label, e_techn, "--o")
!endfunction
!unquoted function AggregationBack(e_from, e_to, e_label) 
    Link_(e_from,e_to, e_label, "o--")
!endfunction
!unquoted function AggregationBack(e_from, e_to, e_label, e_techn) 
    Link_(e_from,e_to, e_label, e_techn, "o--")
!endfunction



' 组合
!unquoted function Composition(e_from, e_to, e_label) 
    Link_(e_from,e_to, e_label, "--*")
!endfunction
!unquoted function Composition(e_from, e_to, e_label, e_techn) 
    Link_(e_from,e_to, e_label, e_techn, "--*")
!endfunction
!unquoted function CompositionBack(e_from, e_to, e_label) 
    Link_(e_from,e_to, e_label, "*--")
!endfunction
!unquoted function CompositionBack(e_from, e_to, e_label, e_techn) 
    Link_(e_from,e_to, e_label, e_techn, "*--")
!endfunction




' 依赖
!unquoted function Dependency(e_from, e_to, e_label) 
    Link_(e_from,e_to, e_label, "..>")
!endfunction
!unquoted function Dependency(e_from, e_to, e_label, e_techn) 
    Link_(e_from,e_to, e_label, e_techn, "..>")
!endfunction
!unquoted function DependencyBack(e_from, e_to, e_label) 
    Link_(e_from,e_to, e_label, "<..")
!endfunction
!unquoted function DependencyBack(e_from, e_to, e_label, e_techn) 
    Link_(e_from,e_to, e_label, e_techn, "<..")
!endfunction


' 关联
!unquoted function Association(e_from, e_to, e_label) 
    Link_(e_from,e_to, e_label, "--")
!endfunction
!unquoted function Association(e_from, e_to, e_label, e_techn) 
    Link_(e_from,e_to, e_label, e_techn, "--")
!endfunction



@enduml