@startuml corlor-define

!include http://plantuml.oss.manerfan.com/material-colors.puml
' uncomment the following line and comment the first to use locally
'!include  material-colors.puml
' Colors
' ##################################
!Black          = '#222222'
!MidnightBlue   = '#363D5D'
!Red            = '#F6363F'
!Pink           = '#F6216E'
!Magenta        = '#A54FBD'
!Green          = '#37A77C'
!Yellow         = '#F97A00'
!Blue           = '#1E98F2'
!CYan           = '#25AFCA'
!AntiqueWhite   = '#FEF2DC'
!Grey           = '#444444'

' Normal Corlor
'---------------------
!NOTE_BG_COLOR          = MD_BGRAY_300
!NOTE_BORDER_COLOR      = MD_BGRAY_300

!NOTE_Q_BG_COLOR        = MD_YELLOW_800
!NOTE_Q_BORDER_COLOR    = MD_YELLOW_800

!EL_BG_COLOR_900        = MD_BLUE_900
!EL_BORDER_COLOR_900    = MD_BLUE_900
!EL_BG_COLOR_800        = MD_BLUE_800
!EL_BORDER_COLOR_800    = MD_BLUE_800
!EL_BG_COLOR_600        = MD_BLUE_600
!EL_BORDER_COLOR_600    = MD_BLUE_600

!EL_BG_COLOR_400        = MD_BLUE_400
!EL_BORDER_COLOR_400    = MD_BLUE_400

!EL_BG_COLOR_300        = MD_BLUE_300
!EL_BORDER_COLOR_300    = MD_BLUE_300

' C4 Colors
' ============================================
'!ELEMENT_FONT_COLOR = '#FFFFFF'

' Person
'!PERSON_BG_COLOR = '#08427B'
'!PERSON_BORDER_COLOR = '#073B6F'
'!EXTERNAL_PERSON_BG_COLOR = '#686868'
'!EXTERNAL_PERSON_BORDER_COLOR = '#8A8A8A'

' System
'!SYSTEM_BG_COLOR = '#1168BD'
'!SYSTEM_BORDER_COLOR = '#3C7FC0'
'!EXTERNAL_SYSTEM_BG_COLOR = '#999999'
'!EXTERNAL_SYSTEM_BORDER_COLOR = '#8A8A8A'

' Database
'!DATABASE_BG_COLOR = '#1168BD'
'!DATABASE_BORDER_COLOR = '#3C7FC0'

' Actor
'!ACTOR_BG_COLOR = '#08427B'
'!ACTOR_BORDER_COLOR = '#073B6F'
'!INTERNAL_ACTOR_BG_COLOR = '#686868'
'!INTERNAL_ACTOR_BORDER_COLOR = '#8A8A8A'

' Container
'!CONTAINER_BG_COLOR = '#438DD5'
'!CONTAINER_BORDER_COLOR = '#3C7FC0'

' Component
'!COMPONENT_BG_COLOR = '#85BBF0'
'!COMPONENT_BORDER_COLOR = '#78A8D8'
'!COMPONENT_FONT_COLOR = Black

@enduml